services:
  - type: web
    name: auto-filter-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: ADMINS
        sync: false
      - key: CHANNELS
        sync: false
      - key: LOG_CHANNEL
        sync: false
